'use client';

import Image from "next/image";
import Code from "./components/code";
import Endpoint from "./components/endpoint";

export default function Home() {
  return (
    <main>
      <header class="bg-slate-100 mb-12">
        <div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
          <div class="sm:flex sm:items-center sm:justify-between">
            <div class="text-center sm:text-left">
              <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">[base_url] API</h1>
              <p class="mt-1.5 text-sm text-gray-500">generated by 🦊 newton</p>
            </div>
            <div class="mt-4 flex flex-col gap-4 sm:mt-0 sm:flex-row sm:items-center">
              <input
                type="text"
                class="block w-full rounded-lg text-gray-800 p-3 shadow-sm sm:max-w-xs sm:text-sm border border-gray-400 focus:ring-indigo-500 focus:border-indigo-500"
                placeholder="Search..."
              />
            </div>
          </div>
        </div>
      </header>
      <div class="grid grid-cols-1 gap-4 lg:grid-cols-5 lg:gap-8 px-8 lg:px-24">
        <div class="h-full rounded-lg">
          <p class="font-medium text-sm pb-3">Endpoints</p>
          <ul class="space-y-1">
            <li>
              <a href="#" class="block rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700">
                [Endpoint title]
              </a>
            </li>
            <li>
              <a href="#" class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                [Endpoint title]
              </a>
            </li>
            <li>
              <a href="#" class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                [Endpoint title]
              </a>
            </li>
            <li>
              <a href="#" class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                [Endpoint title]
              </a>
            </li>
            <li>
              <a href="#" class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                [Endpoint title]
              </a>
            </li>
          </ul>
        </div>
        <div class="rounded-lg lg:col-span-4">
          <div class="grid grid-cols-1 gap-4 mb-12 sm:grid-cols-2 sm:gap-8">
            <div class="rounded-lg">
              <p class="font-extrabold text-xl mb-4">API Reference</p>
              <p class="text-sm leading-loose">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis suscipit arcu quis augue venenatis, quis finibus dolor varius.
                Aliquam eget convallis nulla, in luctus leo. Nulla metus urna, faucibus nec consequat et, rutrum eu est. Morbi sed interdum tellus,
                faucibus bibendum magna. Donec dignissim nisl quis convallis sodales.
                <br></br><br></br>
                Curabitur cursus lacus tortor, et fringilla elit ultrices id.
                Praesent vehicula purus eu quam porttitor fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                inceptos himenaeos. Aenean a tincidunt purus. Proin fringilla at quam id efficitur.
              </p>
            </div>
            <div>
              <div class="mb-6">
                <p class="font-extrabold text-xl mb-4">API Usage</p>
                <Code
                  header="Base URL"
                  code={`https://api.example.com`}
                  language="bash"
                />
              </div>
              <div>
                <p class="font-extrabold text-xl mb-4">Usage Policy</p>
                <p class="text-sm leading-loose">
                  Rate limits are set based on quis tempus est. Ut hendrerit sodales nisi, elementum facilisis augue volutpat non.
                  Aliquam eget consequat erat. Nulla sit amet enim non eros consectetur consequat. Vivamus id elit ac mauris faucibus tempus pulvinar vel ex.
                  Proin a efficitur ipsum.
                </p>
              </div>
            </div>
          </div>
          <hr></hr>
          <Endpoint data={{}} />
        </div>
      </div>
    </main>

  );
}
